export const BEGIN_AJAX_CALL = "BEGIN_AJAX_CALL";
export const AJAX_CALL_ERROR = "AJAX_CALL_ERROR";

export const LOAD_COURSES_SUCCESS = "LOAD_COURSES_SUCCESS";
export const UPDATE_COURSE_SUCCESS = "UPDATE_COURSE_SUCCESS";
export const CREATE_COURSE_SUCCESS = "CREATE_COURSE_SUCCESS";

export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOOUT_SUCCESS = "USER_LOOUT_SUCCESS";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";

export const USER_API_TOKENS_SUCCESS = "USER_API_TOKENS_SUCCESS";

export const LOAD_CONTEST_REQUEST = "LOAD_CONTEST_REQUEST";
export const LOAD_CONTEST_SUCCESS = "LOAD_CONTEST_SUCCESS";
export const LOAD_CONTEST_FAILURE = "LOAD_CONTEST_FAILURE";
export const UPDATE_CONTEST_SUCCESS = "UPDATE_CONTEST_SUCCESS";
export const CREATE_CONTEST_SUCCESS = "CREATE_CONTEST_SUCCESS";

export const LOAD_CONTEST_FILTER_SUCCESS = "LOAD_CONTEST_FILTER_SUCCESS";
export const ORGANIZER_SEARCH_SUCCESS = "ORGANIZER_SEARCH_SUCCESS";
export const SORT_CONTEST_SUCCESS = "SORT_CONTEST_SUCCESS";

export const CHANGE_AUTH_MODEL_VISIBILITY = "CHANGE_AUTH_MODEL_VISIBILITY";

export const AUTH_TOKEN_SUCCESS = "AUTH_TOKEN_SUCCESS";
