export const BEGIN_AJAX_CALL = "BEGIN_AJAX_CALL";
export const AJAX_CALL_ERROR = "AJAX_CALL_ERROR";

export const LOAD_COURSES_SUCCESS = "LOAD_COURSES_SUCCESS";
export const UPDATE_COURSE_SUCCESS = "UPDATE_COURSE_SUCCESS";
export const CREATE_COURSE_SUCCESS = "CREATE_COURSE_SUCCESS";

export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOOUT_SUCCESS = "USER_LOOUT_SUCCESS";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";

export const AUTH_TOKEN_SUCCESS = "AUTH_TOKEN_SUCCESS";